name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/**"

jobs:
  Lint_and_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
      
      - run: npm ci
        working-directory: ./frontend

      - name: Run Lint
        run: npm run lint
        working-directory: ./frontend
      
      - name: Run Test
        run: npm run test
        working-directory: ./frontend