name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - "frontend/"

jobs:
  Lint_&_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"
          cache: npm
      
      - name: Run Lint
        run: npm run lint
      
      - name: Run Test
        run: npm run test